// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-section-alphaxiv-empty'
  | 'item-section-alphaxiv-head-text'
  | 'item-section-alphaxiv-link-label'
  | 'item-section-alphaxiv-sidenav-tooltip';
